"use client";
import { motion } from 'framer-motion';
import { useState } from 'react';
// Import Image from next/image if using real images
// import Image from 'next/image';

export const Testimonials = () => {
  const [activeTestimonial, setActiveTestimonial] = useState(0);

  const testimonials = [
    {
      id: 1,
      quote: "Since implementing BeFitter, we've seen a 15% increase in member retention in just 6 months. Our trainers love how easy it is to manage clients.",
      author: "Jane Cooper",
      position: "Owner",
      gym: "Fitness Evolution",
      image: "/placeholder.jpg" // Replace with actual image path
    },
    {
      id: 2,
      quote: "The branded app makes us look incredibly professional and modern. Members appreciate the personalized plans – it's a huge value-add!",
      author: "Marcus Reynolds",
      position: "Manager",
      gym: "Peak Performance Gym",
      image: "/placeholder.jpg" // Replace with actual image path
    },
    {
      id: 3,
      quote: "The personalized plans generated by the platform have allowed our trainers to take on 30% more clients while delivering better service.", // Cambiado
      author: "Sophie Chen",
      position: "Fitness Director",
      gym: "Urban Health Club",
      image: "/placeholder.jpg" // Replace with actual image path
    }
  ];

  const containerVariants = { /* ... */ };
  const itemVariants = { /* ... */ };

  const currentBgColor = "bg-slate-900"; // Mantiene el fondo oscuro

  return (
    <section className={`${currentBgColor} py-16 md:py-24 text-white`} id="testimonials">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* --- Título Sección (Adaptado) --- */}
        <motion.div /* ... */ className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-100 mb-4">
            See How Gyms Like Yours Are Winning with BeFitter
          </h2>
          <p className="text-slate-300 max-w-3xl mx-auto text-lg">
            Hear directly from gym owners and managers who've transformed their business.
          </p>
          <div className="w-20 h-1 bg-[#007BFF] mx-auto mt-6"></div>
        </motion.div>

        <div className="relative">
          {/* --- Testimonio Activo (Adaptado) --- */}
          <motion.div
            key={activeTestimonial}
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.5 }}
            // Tarjeta adaptada a dark mode
            className="bg-slate-800 rounded-xl shadow-lg p-8 md:p-12 max-w-4xl mx-auto relative z-10 border border-slate-700"
          >
            <div className="flex flex-col md:flex-row gap-8 items-center"> {/* Added items-center */}
              {/* Imagen/Placeholder (Adaptado) */}
              <div className="md:w-1/3 flex justify-center">
                <div className="w-32 h-32 rounded-full bg-slate-700 flex items-center justify-center overflow-hidden border-4 border-[#007BFF]">
                  {/* Placeholder SVG */}
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-16 w-16 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                  </svg>
                  {/* If using Next Image:
                  <Image src={testimonials[activeTestimonial].image} alt={testimonials[activeTestimonial].author} width={128} height={128} className="object-cover" />
                  */}
                </div>
              </div>
              {/* Contenido del Testimonio (Adaptado) */}
              <div className="md:w-2/3 text-center md:text-left"> {/* Centered text on small screens */}
                <svg className="h-8 w-8 md:h-10 md:w-10 text-[#007BFF] mb-4 opacity-40 mx-auto md:mx-0" fill="currentColor" viewBox="0 0 32 32">
                  <path d="M9.352 4C4.456 7.456 1 13.12 1 19.36c0 5.088 3.072 8.064 6.624 8.064 3.36 0 5.856-2.688 5.856-5.856 0-3.168-2.208-5.472-5.088-5.472-.576 0-1.344.096-1.536.192.48-3.264 3.552-7.104 6.624-9.024L9.352 4zm16.512 0c-4.8 3.456-8.256 9.12-8.256 15.36 0 5.088 3.072 8.064 6.624 8.064 3.264 0 5.856-2.688 5.856-5.856 0-3.168-2.304-5.472-5.184-5.472-.576 0-1.248.096-1.44.192.48-3.264 3.456-7.104 6.528-9.024L25.864 4z" />
                </svg>
                <p className="text-slate-300 text-lg md:text-xl mb-6 italic"> {/* Added italic */}
                  "{testimonials[activeTestimonial].quote}"
                </p>
                <div>
                  <p className="font-bold text-gray-100">
                    {testimonials[activeTestimonial].author}
                  </p>
                  <p className="text-slate-400">
                    {testimonials[activeTestimonial].position}, {testimonials[activeTestimonial].gym}
                  </p>
                </div>
              </div>
            </div>

            {/* Triángulo decorativo adaptado */}
            <div className="absolute -bottom-3 right-10 transform rotate-45 w-6 h-6 bg-slate-800 border-r border-b border-slate-700"></div>
          </motion.div>

          {/* Navegación (Adaptado) */}
          <div className="flex justify-center mt-10 space-x-2">
            {testimonials.map((_, index) => (
              <button
                key={index}
                onClick={() => setActiveTestimonial(index)}
                className={`w-3 h-3 rounded-full transition-colors duration-300 ${
                  activeTestimonial === index ? "bg-[#007BFF]" : "bg-slate-600 hover:bg-slate-500" // Colores de puntos adaptados
                }`}
                aria-label={`Go to testimonial ${index + 1}`}
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};